const RNG = require("./RNG.js");

var firstNames = [
  "Anno",
  "Panteleon",
  "Orderic",
  "Sancho",
  "Bucca",
  "Arbitio",
  "Ledger",
  "Ricchar",
  "Halinard",
  "Willibrord",
  "Reginar",
  "Gararic",
  "Gararic",
  "Walcaud",
  "Merimas",
  "Dagaric",
  "Crassus",
  "Theuderic",
  "Marcomir",
  "Alberic",
  "Bobuth",
  "Thakkarlig",
  "Thondraec",
  "Nedden",
  "Dwogratin",
  "Grarnec",
  "Fikherlum",
  "Dodoir",
  "Khouthaer",
  "Thongraet",
  "Illithor",
  "Naertho",
  "Inchel",
  "Emmyth",
  "Ayred",
  "Elpaerae",
  "Albondiel",
  "Orndacil",
  "Uldreiyn",
  "Zaltarish",
  "Almithara",
  "Tisharu",
  "Sphiel",
  "Nylaathria",
  "Shearah",
  "Ghilanna",
  "Salihn",
  "Talila",
  "Thasitalia",
  "Merialeth",
  "Rain",
  "Aloha",
  "Lazuli",
  "Herb",
  "Bim",
  "Barley",
  "Walnut",
  "Astro",
  "Axis",
  "Sprinkle",
  "Crisdyr",
  "Jarmon",
  "Leoellan",
  "Lamtar",
  "Clerdil",
  "Yorladar",
  "Rainrath",
  "Eirlamar",
  "Vicphar",
  "Audlamar",
  "Matfrid",
  "Bovo",
  "Bingo",
  "Hartmut",
  "Hildebald",
  "Dudo",
  "Chlotar",
  "Samo",
  "Wala",
  "Ouen",
  "Madelgarde",
  "Katie",
  "Tanta",
  "May",
  "Engelberga",
  "Rosamund",
  "Tanta",
  "Emily",
  "Tavia",
  "Fallon",
  "Linda",
  "Duenna",
  "Adaltrude",
  "Lenora",
  "Regina",
  "May",
  "Tatiana",
  "Pansy",
  "Kelsey",
  "Nantechildis",
  "Ceufroy",
  "Humbert",
  "Fastolph",
  "Dodo",
  "Heribert",
  "Imbert",
  "Audoen",
  "Leuthere",
  "Hagen",
  "Childeric",
  "Fulcaire",
  "Sagramor",
  "Roderic",
  "Ricbodo",
  "Marmadoc",
  "Richomer",
  "Badegisel",
  "Orlando",
  "Guido",
  "Rathar",
  "Walaric",
  "Gouzlim",
  "Adelard",
  "Gerontius",
  "Theobald",
  "Jolly",
  "Goisfrid",
  "Bingo",
  "Benild",
  "Anno",
  "Willichar",
  "Brocard",
  "Panteleon",
  "Hildebald",
  "Bilcuzal",
  "Chlodmer",
  "Norbert",
  "Hunald",
  "Marroc",
  "Theudebald",
  "Nun",
  "Llund",
  "Hridr",
  "Khesnoll",
  "Geillvand",
  "Unngold",
  "Tyonnith",
  "Tufveikr",
  "Prinnuyvirn",
  "Bopluludr",
  "Khuh",
  "Seh",
  "Ga",
  "Sholmof",
  "Gwaecu",
  "Makeil",
  "Steshesh",
  "Rhilgrann",
  "Thugreafthu",
  "Friymiolde",
  "Kran",
  "Grerv",
  "Dhub",
  "Druat",
  "Golk",
  "Totzak",
  "Vognoub",
  "Krunguab",
  "Zucriag",
  "Bretto",
  "Tabbun",
  "Bhoda",
  "Ruruah",
  "Choetoe",
  "Ashai",
  "Traka",
  "Esi",
  "Skudis",
  "Eenaah",
  "Biza"
];

var lastNames = [
  "Undertree",
  "Proudbottom",
  "Hairyfoot",
  "Riverhopper",
  "Gamwich",
  "Fleetfoot",
  "Oakbottom",
  "Gawkroger",
  "Swiftfoot",
  "Oldbuck",
  "Thornburrow",
  "Greenhand",
  "Fleetfoot",
  "North-took",
  "Featherbottom",
  "Gluttonbelly",
  "Noakes",
  "Leafwalker",
  "Underburrow",
  "Twofoot",
  "Runebelly",
  "Ingotarm",
  "Opalmane",
  "Mountainthane",
  "Beastarmour",
  "Hardbranch",
  "Largeblade",
  "Caveshaper",
  "Dragonbraids",
  "Shadowbraids",
  "Wysakian",
  "Heidi",
  "Eilsandoral",
  "Hercan",
  "Thewarin",
  "Vahorn",
  "Virfina",
  "Olaric",
  "Olarora",
  "Brynala",
  "Valsys",
  "Ulabella",
  "Inalamin",
  "Gilphine",
  "Wranharice",
  "Sarvyre",
  "Fenqen",
  "Eladithas",
  "Wranjor",
  "Gendove",
  "Mossymint",
  "Silkblossom",
  "Mistytwist",
  "Falconfoam",
  "Frozengrace",
  "Fernfleck",
  "Woodpond",
  "Cricketfeet",
  "Cloudylace",
  "Beechwillow",
  "Elydark",
  "Zinran",
  "Farvalur",
  "Chaesandoral",
  "Wyngolor",
  "Reynala",
  "Quinan",
  "Daewarin",
  "Ravaric",
  "Sylxidor",
  "Riverhopper",
  "Grubb",
  "Cutton",
  "Oakbottom",
  "Fairbairn",
  "Maggot",
  "Whitbottom",
  "Pott",
  "Banks",
  "Hlothran",
  "Bunce",
  "Noakesburrow",
  "Baggins",
  "Hopesinger",
  "Proudbody",
  "Sackville",
  "Boffin",
  "Fallohide",
  "Silentfoot",
  "Greenhand",
  "Bilberry",
  "Silentfoot",
  "Finnagund",
  "Pott",
  "Silverstring",
  "Butcher",
  "Clayhanger",
  "Littlefoot",
  "Wanderfoot",
  "Maggot",
  "Brockhouse",
  "Underburrow",
  "Chubb",
  "Bolger-Baggins",
  "Boffin",
  "Underfoot",
  "Brown",
  "Bottomhill",
  "Whitfoot",
  "Longriver",
  "Brandybuck",
  "Heathertoes",
  "Dewfoot",
  "Leafwalker",
  "Featherbottom",
  "Greenhand",
  "Sandheaver",
  "Noakes",
  "Grubb",
  "Galbassi",
  "Farfoot",
  "Littlefoot",
  "Thornburrow",
  "Tunnelly",
  "Sandheaver",
  "Noakesburrow",
  "Longriver",
  "Goodsong",
  "Baggins",
  "Lothran",
  "Longbottom",
  "North-took",
  "Whitfoot",
  "Bolger",
  "Twofoot",
  "Longfoot",
  "Brandybuck",
  "Gardner",
  "Brown",
  "Emberswallow",
  "Masterflower",
  "Fusedown",
  "Greensnow",
  "Roughsteel",
  "Netherbrook",
  "Lightningarrow",
  "Ravenbringer",
  "Spiritfist",
  "Mountainbough",
  "Woodbelly",
  "Dustbrand",
  "Darkless",
  "Mourningeye",
  "Earthstalker",
  "Hallowedslayer",
  "Gloomfire",
  "Thunderlance",
  "Autumnbreaker",
  "Clanhell",
  "Dawnstrider",
  "Strongbash",
  "Eaglemore",
  "Barleyswift",
  "Wolfswift",
  "Netherflame",
  "Laughingcrusher",
  "Feathertail",
  "Dayfallow",
  "Dusktail",
  "Cliffswift",
  "Silenttalon",
  "Firespire",
  "Willowdraft",
  "Earthshot",
  "Doomhell",
  "Snowgrain",
  "Gloomwalker",
  "Hazesword",
  "Grandstream"
];

var fullNames = [
  "Fredericus the Deviant",
  "Euvrouin the Bald",
  "Gilebert the Clever",
  "Urian the Guardian",
  "Salaman the Smiling",
  "Symkyn of the Snow",
  "Nick the Lion",
  "Nicolas the Brute",
  "Guarinet the Champion",
  "Ronald the Warm",
  "Maughtild the Stubborn",
  "Aelis the Creature",
  "Aleneite the Selfish",
  "Saloua the Defender",
  "Imagantia the Honest",
  "Lunet the Fierce",
  "Catrain the Brilliant",
  "Elyzabeth the Righteous",
  "Rosemond the Gentlewoman",
  "Lilias the Giant",
  "Archbishop Seri",
  "Monk Aurri",
  "Viscount Euvrouin",
  "Count Dreu",
  "Landgrave Cristoffle",
  "Vicar Pearse",
  "Admiral Galter",
  "Knight Simkin",
  "Peasant Sam",
  "Lord Nicolin",
  "Peasant Henriot",
  "Vicar Ernest",
  "Peasant Ludovicus",
  "Count Davi",
  "Monk Tobyn",
  "King Adie",
  "Yeoman Acelin",
  "Cardinal Hurrey",
  "Baronet Tobye",
  "Admiral Gerrart",
  "Queen Gennon",
  "Queen Tiffan",
  "Squire Luanda",
  "Peasant Juliana",
  "Duchess Emmony",
  "Princess Consort Madlin",
  "Grand Duchess Richmal",
  "Princess Lunete",
  "Countess Ela",
  "Countess Isota"
];

function getName() {
  var name = "";

  if (RNG() < 0.1) {
    let n = Math.round(RNG(fullNames.length));
    name = fullNames[n];
  } else {
    let f = Math.round(RNG(firstNames.length));
    let l = Math.round(RNG(lastNames.length));
    name =  firstNames[f] + " " + lastNames[l];
  }
  return name;
}

module.exports = getName;
